export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL';
