export const FETCH_LANDING_ORDER_START = 'FETCH_LANDING_ORDER_START';
export const FETCH_LANDING_ORDER_SUCCESS = 'FETCH_LANDING_ORDER_SUCCESS';
export const FETCH_LANDING_ORDER_FAILED = 'FETCH_LANDING_ORDER_FAILED';
